### ISSUE TITLE
アイコンが更新されない

### ISSUE THREAD

**Issue by ryutarosuda** [hummingbird-jp/stat-flutter#1]
アイコンが更新されないで:x:のままになる。
ただ、`isInView`は定期的に`true`になる。

**Comment by yhakamay** [comment]
closed with [28b2b3684007a4ebb536103fe43a037cd4959ddf](https://github.com/hummingbird-jp/stat-flutter/commit/28b2b3684007a4ebb536103fe43a037cd4959ddf)
